<head>
  <title>Static Header</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Tmp</title>
  <meta name="description" content="Calendar  Apartments-for-rent">
  <meta name="keywords" lang="en" content="">
  <meta name="author" lang="en" content="Kjetil Larsen">
  <meta name="robots" content="noindex, nofollow">
  
  <link rel="StyleSheet" href="/afr/css/afr_base.css?ts=1424078395" type="text/css" media="screen"/>
  
</head>
<body>
<a href="/">Home</a>
<br>
<br>


